language: java
sudo: required
jdk:
  - oraclejdk8
before_install:
- git clone --depth 1 https://github.com/Cooperate-Project/BuildUtils.git /tmp/BuildUtils
- . /tmp/BuildUtils/travisci/setup.sh
install: true
script:
- mavenBuild.sh
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:  
  - secure: "SHq0WmujCSwF4WspYRoMzYNrZtRWit/By9bfNCBaJdzKUSlIUnUu4MCC3TcYcM32qpE29fAYMEOo+uaw9IYO+9j47BY1DdWPiB0Em3CadmFAoPgrbM5Eth/4t3HLmWEyom3Q28R2VmNA8xldwQYYu63AubmZ+OOku9phhIxuEJ0="