language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
- git clone --depth 1 https://github.com/Cooperate-Project/BuildUtils.git /tmp/BuildUtils
- . /tmp/BuildUtils/travisci/setup.sh
install: true
script:
- mavenBuild.sh
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:  
  - secure: "bYpeuIPqL75MjUaI541mCc18jfCp+T/AIUmTqDJu33VeJIEFwYxYxPYU+xGd4yyp6NQGUs8OD5kB0ZJ6XLhQl28gXg6jTERKSMcpQIe10Rxz0f/5Y6yqTeAHgBwPj8fNLv7YDOzOuCIa8FneMZ4dkvPhQiWhyLGJil6BVzNJ2Mw="
  - secure: "KPvtol+6jncx1Pb2VsvGGQUzH5G1dvvUe8Y128ZzsooEC9nJXkZKltbGDnmwoQ2/tZS+PSFIkJCh5MNg5B+c5U3hViXknmGrrLQY6F2Tg2DIIW9fAhwWdxa1s5NGnbAAeKllXeHds5QsYpQsoi2+mowR8+RJOMm7co9gNd8FHrc="
  - secure: "hWHWGXw8dv0usBhqjd1x9aemURE1Oj2rCAZxGccV34QqA8nOyxHt0h4ttEM/mJe4+pUR8xcIavJXgKEHqxszWX0h4LDgY2izukc+K1fm+ZQWnvYzP/buYpPBF+lpLIRlavmBLlY2ZxjMUGhUQJ191t6snDL9ney39bDxf1sFNYY="